/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfacegrafica;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;


/**
 *
 * @author Gazebo
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafica
     */
    
        ImageIcon iconOFF = new ImageIcon("./Images/Botão Desligado.png");
        ImageIcon iconON = new ImageIcon("./Images/Botão Ligado.png");
        boolean btnRelay1status = false;
        boolean btnRelay2status = false;
        boolean btnRelay3status = false;
        
        SerialComunication serialComunication = new SerialComunication();
        
    public InterfaceGrafica() {
        initComponents();
        setLocationRelativeTo(null);  
        
        serialComunication.ReadValues();
        
        Timer timer = new Timer(1000, new loop());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHumidity = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        btnRelay1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRelay3 = new javax.swing.JButton();
        btnRelay2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUTOMAÇÃO RESIDENCIAL");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setText("PORTA:");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setText("AUTOMAÇÃO RESIDENCIAL");

        lblPort.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblPort.setText("ARDUINO NÃO ENCONTRADO");

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setText("UMIDADE:");

        lblHumidity.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblHumidity.setText("0");

        jLabel5.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel5.setText("TEMPERATURA:");

        lblTemperature.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblTemperature.setText("0");

        btnRelay1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\AutomacaoResidencial\\Images\\Botão Desligado.png")); // NOI18N
        btnRelay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelay1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        btnRelay3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\AutomacaoResidencial\\Images\\Botão Desligado.png")); // NOI18N
        btnRelay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelay3ActionPerformed(evt);
            }
        });

        btnRelay2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\AutomacaoResidencial\\Images\\Botão Desligado.png")); // NOI18N
        btnRelay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelay2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHumidity)
                            .addComponent(lblTemperature)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(lblPort)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRelay1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelay3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelay2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPort)
                            .addComponent(jLabel1))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblHumidity))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemperature)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnRelay1)
                        .addGap(32, 32, 32)
                        .addComponent(btnRelay2)
                        .addGap(27, 27, 27)
                        .addComponent(btnRelay3)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelay1ActionPerformed
        // TODO add your handling code here:
        if(!btnRelay1status){
            btnRelay1.setIcon(iconON);
            btnRelay1status = true;
            serialComunication.sendValues(1);
        }else{
            btnRelay1.setIcon(iconOFF);
            btnRelay1status = false;
            serialComunication.sendValues(4);
        }
        
    }//GEN-LAST:event_btnRelay1ActionPerformed

    private void btnRelay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelay3ActionPerformed
        // TODO add your handling code here:
        if(!btnRelay3status){
            btnRelay3.setIcon(iconON);
            btnRelay3status = true;
            serialComunication.sendValues(3);
        }else{
            btnRelay3.setIcon(iconOFF);
            btnRelay3status = false;
            serialComunication.sendValues(6);
        }
    }//GEN-LAST:event_btnRelay3ActionPerformed

    private void btnRelay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelay2ActionPerformed
        // TODO add your handling code here:
        if(!btnRelay2status){
            btnRelay2.setIcon(iconON);
            btnRelay2status = true;
            serialComunication.sendValues(2);
        }else{
            btnRelay2.setIcon(iconOFF);
            btnRelay2status = false;
            serialComunication.sendValues(5);
        }
    }//GEN-LAST:event_btnRelay2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelay1;
    private javax.swing.JButton btnRelay2;
    private javax.swing.JButton btnRelay3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHumidity;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblTemperature;
    // End of variables declaration//GEN-END:variables



class loop implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            lblHumidity.setText(Constants.getHumidity());
            lblTemperature.setText(Constants.getTemperature());
            lblPort.setText(Constants.getPort());
        }
    
}



}

